name: Session proposal
description: Propose to chair a breakout session at TPAC
labels: ["session"]
body:

  - type: markdown
    attributes:
      value: |
        Thank you for proposing to chair a TPAC breakout session.
        Please review the [good practices for session chairs](https://github.com/w3c/tpac-breakouts/wiki/Good-Practices-for-Session-Chairs).
        Use issue comments for discussion of the session. Please avoid editing the markdown directly except to add links to materials as described below.

  - type: textarea
    id: description
    attributes:
      label: Session description
      description: |
        Simple markdown only please (inline formatting, links, lists).
        Note: Please ensure that the session is [in scope for a TPAC breakout](https://github.com/w3c/tpac-breakouts/wiki/Policies#session-scope).
    validations:
      required: true

  - type: input
    id: goal
    attributes:
      label: Session goal(s)
    validations:
      required: true

  - type: textarea
    id: chairs
    attributes:
      label: Additional session chairs (Optional)
      description: |
        GitHub identities of additional session chairs other than you. Space- or comma-separated list.
    validations:
      required: false

  - type: input
    id: shortname
    attributes:
      label: IRC channel (Optional)
      description: |
        Shortname for the IRC channel. If not provided, channel name will be generated from the session title.
    validations:
      required: false

  - type: dropdown
    id: attendance
    attributes:
      label: Attendance
      description: |
        TPAC breakouts sessions are usually open to the public (including remote attendees). Please only select “Restricted” if there is a compelling reason why the session should only be open to TPAC registrants.
      options:
        - Anyone may attend (Default)
        - Restricted to TPAC registrants
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Preferences

  - type: dropdown
    id: duration
    attributes:
      label: Session duration
      options:
        - 60 minutes (Default)
        - 30 minutes
    validations:
      required: true

  - type: textarea
    id: conflicts
    attributes:
      label: Scheduling conflicts (Optional)
      description: |
        Please list any sessions for which you have a strong preference to avoid a scheduling conflict.
        Space- or comma-separated list of sessions identified by issue numbers in this GitHub repo (e.g., `#32 #18`).
    validations:
      required: false

  - type: dropdown
    id: capacity
    attributes:
      label: Room capacity
      description: |
        Estimate of in-person attendance.
      options:
        - Don't know (Default)
        - Small (fewer than 20 people)
        - Large (20-45 people)
        - Really quite large (more than 45 people)
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
      label: Comments (Optional)
      description: |
        Any additional input, including timing constraints, that we should be aware of.
    validations:
      required: false

  - type: textarea
    id: materials
    attributes:
      label: Meeting materials
      description: |
        As the agenda and meeting materials become available, you will be able to update your session description in markdown to add links. Similarly, after the meeting, you can link to minutes.

        **PLEASE ONLY EDIT BY REPLACING @@ with URLs!**
      value: |
        - Agenda: @@
        - Slides: @@
        - Minutes: @@
