name: Validate breakout session issue

on:
  issues:
    # Details for types below can be found at:
    # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=edited#issues
    types:
      # Job triggered when an issue is created or re-opened
      - opened
      - reopened

      # ... gets "edited" (title or body updated)
      - edited

      # ... or gets a new label
      - labeled

jobs:
  validate-session:
    name: Validate breakout session
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to TPAC breakout session project
        if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
        uses: actions/add-to-project@v0.5.0
        with:
          # We're only interested in "session" issues.
          labeled: session

          # URL of the annual TPAC XXXX breakout project.
          # The PROJECT_OWNER and PROJECT_NUMBER variables must be defined on
          # the repository. PROJECT_OWNER_TYPE needs to be set to "user" if
          # project belongs to a user. It may be omitted otherwise (or set to
          # 'org"').
          project-url: https://github.com/${{vars.PROJECT_OWNER_TYPE || 'org'}}s/${{vars.PROJECT_OWNER}}/projects/${{vars.PROJECT_NUMBER}}

          # A valid Personal Access Token (classic version) with project scope
          # needs to be added as secret to the repo, because the action uses
          # the GraphQL API under the hoods.
          github-token: ${{ secrets.GRAPHQL_TOKEN }}
